#+TITLE: Emacs configuration
#+AUTHOR: Tommi Kivimäki

* Emacs literate configuration

** Configure package repos

#+BEGIN_SRC emacs-lisp
(require 'package)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
			 ("marmalade" . "https://marmalade-repo.org/packages/")))
#+END_SRC


** Packages to be installed

#+BEGIN_SRC emacs-lisp
(defvar my-packages '(beacon
		      dired-narrow
		      flycheck
		      magit
		      markdown-mode
		      swift-mode
		      which-key))
#+END_SRC

Installing packages

#+BEGIN_SRC emacs-lisp
(dolist (p my-packages)
  (unless (package-installed-p p)
    (package-refresh-contents)
    (package-install p))
  (add-to-list 'package-selected-packages p))
#+END_SRC


** Setting a theme

#+BEGIN_SRC emacs-lisp
(load-theme 'tango-dark)
#+END_SRC


** Configuring the window

Display line numbers
#+BEGIN_SRC emacs-lisp
(when (version<= "26.0.50" emacs-version )
  (global-display-line-numbers-mode))
#+END_SRC

Set default window size
#+BEGIN_SRC emacs-lisp
(if (display-graphic-p)
   (progn
     (setq initial-frame-alist
	    '(
	      (tool-bar-lines . 0)
	      (width . 95)
	      (height . 92)))
     (setq default-frame-alist
	    '(
	      (tool-bar-lines . 0)
	      (width . 95)
	      (height . 92))))
 (progn
   (setq initial-frame-alist '((tool-bar-lines . 0)))
   (setq default-frame-alist '((tool-bar-lines . 0)))))
#+END_SRC

Change font size
#+BEGIN_SRC emacs-lisp
(defun zoom-in ()
  (interactive)
  (let ((x (+ (face-attribute 'default :height)
	      10)))
    (set-face-attribute 'default nil :height x)))

(defun zoom-out ()
  (interactive)
  (let ((x (- (face-attribute 'default :height)
	      10)))
    (set-face-attribute 'default nil :height x)))

(define-key global-map (kbd "C-1") 'zoom-in)
(define-key global-map (kbd "C-0") 'zoom-out)
#+END_SRC

Disable scroll bar
#+BEGIN_SRC emacs-lisp
;;(scroll-bar-mode -1)
#+END_SRC

Remember cursor position when reopening files
#+BEGIN_SRC emacs-lisp
(setq save-place-file (expand-file-name "places" user-emacs-directory))
(setq save-place-forget-unreadable-files nil)
(save-place-mode 1)
#+END_SRC

Enable narrow-to-region mode. "C-x n n" Restrict editing in this
buffer to current region.
#+BEGIN_SRC emacs-lisp
(put 'narrow-to-region 'disabled nil)
#+END_SRC

Use visual bell instead of audio bell
#+BEGIN_SRC emacs-lisp
(setq visible-bell t)
#+END_SRC


** Beacon (part of window config)
[[https://github.com/Malabarba/beacon][Beacon]]
Visual cursor position when scrolling and jumping
#+BEGIN_SRC emacs-lisp
(beacon-mode 1)
(setq beacon-blink-duration 0.8)
#+END_SRC


** Emacs system configuration
Set garbage collection to 20MB instead of 0.76MB default.
Speeds up certain operations

#+BEGIN_SRC emacs-lisp
(setq gc-cons-threshold 20000000)
#+END_SRC

Direct auto save files
#+BEGIN_SRC emacs-lisp
(setq auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))
#+END_SRC

Set back-up directory
#+BEGIN_SRC emacs-lisp
(setq backup-directory-alist `(("." . ,(expand-file-name
 					(concat user-emacs-directory "backups")))))
#+END_SRC

Set how many backups are stored
#+BEGIN_SRC emacs-lisp
(setq make-backup-files t
     backup-by-copying t
     delete-old-versions t
     kept-new-versions 2
     kept-old-versions 3
     version-control t)
#+END_SRC

Allow following symlinks
#+BEGIN_SRC emacs-lisp
(setq vc-follow-symlinks t)
#+END_SRC

Enable using right side ALT as a modifier and not META key
#+BEGIN_SRC emacs-lisp
(setq mac-option-key-is-meta t)
(setq mac-right-option-modifier nil)
#+END_SRC

Get rid of start-up screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-screen t)
#+END_SRC


** Markdown mode
Enable visual line mode
#+BEGIN_SRC emacs-lisp
(add-hook 'markdown-mode-hook 'visual-line-mode)
#+END_SRC


** dired-mode
Use 'a' to visit a directory without creating a new buffer
#+BEGIN_SRC emacs-lisp
(put 'dired-find-alternate-file 'disabled nil)
#+END_SRC

Copy recursively on C
#+BEGIN_SRC emacs-lisp
(setq dired-recursive-copies 'always)
#+END_SRC

dired-narrow starts fussy search with "/"
[[http://pragmaticemacs.com/emacs/dynamically-filter-directory-listing-with-dired-narrow/][dired-narrow]]
#+BEGIN_SRC emacs-lisp
(require 'dired)
(define-key dired-mode-map (kbd "/") 'dired-narrow-fuzzy)
#+END_SRC


** Magit
[[https://github.com/magit/magit/wiki/Cheatsheet][Magit Cheat Sheet]]
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x g") 'magit-status)
#+END_SRC


** Which-key
[[https://github.com/justbur/emacs-which-key][Which key]]
Minor mode displaying key bindings. Enter a shortcut and wait 1 second
to see available options
#+BEGIN_SRC emacs-lisp
(require 'which-key)
(which-key-mode)
;; Show VIM keys too
(setq which-key-allow-evil-operators t)
(setq which-key-show-operator-stage-maps t)
#+END_SRC


** Flycheck
[[http://www.flycheck.org/en/latest/][Flycheck]]
Syntax highlighting. Requires installing local linters e.g 'npm
install eslint'
#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook #'global-flycheck-mode)
#+END_SRC


** Org-mode
[[https://orgmode.org/worg/doc.html][Orgmode]]
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/Documents/org/")

;; Setup all the files to be used
(setq org-agenda-files (list "~/Documents/org/todo.org"
			     "~/Documents/org/notes.org"))

;; "M-x notes" to quickly open notes
(defun notes()
  (interactive)
  (find-file "~/Documents/org/notes.org"))

;; Adds a timestamp when a todo is marked as DONE
(setq org-log-done t)

(add-hook 'org-mode-hook 'auto-fill-mode)

;; Store link with "C-c l". Paste it with "C-c C-l"
(global-set-key (kbd "C-c l") 'org-store-link)
(global-set-key (kbd "C-c a") 'org-agenda)
;; Capture todo template (Create a todo: "C-c c t")
(define-key global-map (kbd "C-c c") 'org-capture)
;;(global-set-key (kbd "C-b") 'org-switchb)

;; Open agande in the current window
(setq org-agenda-window-setup (quote current-window))

(setq org-capture-templates
      '(("t" "todo" entry (file+headline "~/Documents/org/todo.org" "Todos")
	 "* TODO [#B] %?\nSCHEDULED: %(org-insert-time-stamp (org-read-date nil t \"+0d\"))\n")))


;; Configuring TODO states. These can be configured at the top of a file too.
(setq org-todo-keywords
  '((sequence "TODO" "IN-PROGRESS" "WAITING" "DONE")))
;; Set faces for todos
(setq org-todo-keyword-faces '(("TODO" . (:foreground "#C2222D" :weight bold))
		      ("IN-PROGRESS" . (:foreground "#FFBF00" :weight bold))
		      ("WAITING" . (:foreground "#DE8ED5" :weight bold))
		      ("DONE" . (:foreground "#73D115" :weight bold))))

;; Set priorities
(setq org-highest-priority ?A)
(setq org-lowest-priority ?C)
(setq org-default-priority ?B)
;; Set priority faces
(setq org-priority-faces '((?A . (:foreground "#C2222D" :weight bold))
			   (?B . (:foreground "#FFBF00"))
			   (?C . (:foreground "#"))))

;; Set tag alignment for org-mode and hook to run alignment after typing a tag
(setq org-tags-column (- 14 (window-body-width)))
;; (add-hook 'org-ctrl-c-ctrl-c-hook 'org-align-all-tags)
(add-hook 'org-insert-heading-hook 'org-align-all-tags)
#+END_SRC
